version: '3.8'

services:
  app:
    container_name: app
    build: .
    ports:
      - '3000:3000'
    volumes:
      - .:/app
      - /app/tmp
    environment:
      - AIR_API_LOG_ENABLED=true
      - AIR_DEBUG=true
      - AIR_TMP_DIR=/app/tmp
    command: air
    depends_on:
      - db

  db:
    image: mysql:8.0
    container_name: db
    restart: always
    environment:
      MYSQL_DATABASE: 'todoapp'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: '12345678'
      MYSQL_ROOT_PASSWORD: '12345678'
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - db_data:/var/lib/mysql
      - db_logs:/var/log/mysql
      - db_conf:/etc/mysql/conf.d/

volumes:
  db_data:
  db_logs:
  db_conf:
